#!/usr/bin/env bash

# ================================================================================
# =                                    BACKUP                                    =
# ================================================================================

# Backup notes, code, configuration files, and databases
# - Sends to local pi (R1) and cloud B2 (R2) Restic repositories
# - Prunes old snapshots, keeping last 1 or 7

NAME=${0##*/}

REPOSITORIES=("$R1" "$R2")

backup_integrity() {
    for repo in "${REPOSITORIES[@]}"; do
        restic --repo "$repo" check --read-data-subset=5%
    done
}

backup_stats() {
    for repo in "${REPOSITORIES[@]}"; do
        restic --repo "$repo" stats --mode=raw-data
    done
}

backup() {
    while read -r tag paths; do
        restic_backup "$tag" $paths
    done < <(python3 "$HOME/parsers/inventory.py" paths "$HOSTNAME" "$@")
}

restic_backup() {
    local tag="$1"
    shift

    local paths=()
    for path in "$@"; do
        # If path exists on system, append to paths array
        [[ -e "$path" ]] && paths+=("$path")
    done
    # If paths array is empty, return early
    ((${#paths[@]} == 0)) && return

    for repo in "${REPOSITORIES[@]}"; do
        restic --repo "$repo" backup "${paths[@]}" --tag "$tag"
        # Group by tags and hosts to prevent path changes from creating orphaned snapshots
        restic --repo "$repo" forget --tag "$tag" --host "$HOSTNAME" --keep-last 7 --group-by tags,hosts --prune
    done
}

main() {
    case "$1" in
        integrity) backup_integrity ;;
        stats) backup_stats ;;
        -h | --help)
            echo "Usage: $NAME [integrity|stats|target...]"
            ;;
        *) backup "$@" ;;
    esac
}

main "$@"
