#!/usr/bin/env bash

# ================================================================================
# =                                    BACKUP                                    =
# ================================================================================

# Backup notes, code, configuration files, and databases
# - Sends to local pi (R1) and cloud B2 (R2) Restic repositories
# - Prunes old snapshots, keeping last 1 or 7

set -euo pipefail

NAME=${0##*/}

REPOSITORIES=("$R1" "$R2")

backup_integrity() {
    for repo in "${REPOSITORIES[@]}"; do
        restic --repo "$repo" check --read-data-subset=5%
    done
}

backup_stats() {
    for repo in "${REPOSITORIES[@]}"; do
        restic --repo "$repo" stats --mode=raw-data
    done
}

restic_backup() {
    local cmd="restic"
    [[ "$1" == "true" ]] && cmd="sudo --preserve-env restic"
    shift

    local tag="$1"
    shift

    local paths=()
    for path in "$@"; do
        # If path exists on system, append to paths array
        [[ -e "$path" ]] && paths+=("$path")
    done
    # If paths array is empty, return early
    ((${#paths[@]} == 0)) && return

    for repo in "${REPOSITORIES[@]}"; do
        $cmd --repo "$repo" backup "${paths[@]}" --tag "$tag"
        # Group by hosts and tags to prevent path changes from creating orphaned snapshots
        # Restic forget never needs sudo
        restic --repo "$repo" forget --host "$HOSTNAME" --tag "$tag" --keep-last 7 --group-by hosts,tags --prune
    done
}

backup() {
    # When read gets more words than variables,
    # it puts the remaining words into the last variable
    # For modules with multiple paths, each path gets assigned to paths correctly
    while read -r sudo tag paths; do
        restic_backup "$sudo" "$tag" $paths # $paths should be unqouted to pass in separate args for each path
    done < <(python3 "$HOME/parsers/inventory.py" paths "$HOSTNAME" "$@")
}

main() {
    case "${1:-}" in
        integrity) backup_integrity ;;
        stats) backup_stats ;;
        -h | --help)
            echo "Usage: $NAME [integrity|stats|target...]"
            ;;
        *) backup "$@" ;;
    esac
}

main "$@"
